on:
  workflow_call:
    inputs:
      major_minor_patch:
        required: true
        type: string
      store_app_id:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: PROD

    env:
      ARTIFACT_DIRECTORY: artifact

    steps:
      - name: debug_version
        run: |
          echo "${{inputs.major_minor_patch}}"

      - uses: actions/download-artifact@v4
        with:
          name: msixupload
          path: ${{ env.ARTIFACT_DIRECTORY }}

      - uses: isaacrlevin/windows-store-action@1.0
        name: Publish to Store
        with:
          tenant-id: ${{ secrets.AZURE_AD_TENANT_ID }}
          client-id: ${{ secrets.AZURE_AD_APPLICATION_CLIENT_ID }}
          client-secret: ${{ secrets.AZURE_AD_APPLICATION_SECRET }}
          app-id: ${{ inputs.store_app_id }}
          package-path: "${{ env.ARTIFACT_DIRECTORY }}"

      - uses: softprops/action-gh-release@v2
        name: Release
        with:
          tag_name: ${{inputs.major_minor_patch}}
