name: Build and Deploy UWP

on:
  push:
    branches:
      - release/*
  workflow_dispatch:

jobs:
  build:
    uses: "./.github/workflows/build.yml"
    secrets: inherit
    with:
      solution_name: "Yugen.Mosaic.sln"
      project_name: "Yugen.Mosaic.Uwp"

  deploy:
    uses: "./.github/workflows/deploy.yml"
    needs: [build]
    secrets: inherit
    with:
      store_app_id: 9PF0S24CX0D4
      major_minor_patch: ${{needs.build.outputs.major_minor_patch}}

  deploy_new:
    uses: "./.github/workflows/deploy-new.yml"
    needs: [build]
    secrets: inherit
    with:
      store_app_id: 9PF0S24CX0D4
      major_minor_patch: ${{needs.build.outputs.major_minor_patch}}
